apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website-techdocs
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/blob/master/OWNERS.md
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
